#define PACKET_MAX_SIZE 1600
#define DOMAIN_MAX_SIZE 300

#define CNAME_DOMAINS_MAP_MAX_SIZE 500
#ifdef TUN_MODE
#define NAT_MAP_MAX_SIZE 50000
#endif

#define STAT_PRINT_TIME 10
#define DOMAINS_UPDATE_TIME 60 * 60 * 24
#define DOMAINS_ERROR_UPDATE_TIME 60

#define ANTIBLOCK_VERSION "2.0.0"
